ja:
  languageName: 日本語
  title: 神道データベース
  hasCJKLanguage: true
  weight: 1
  author:
    name: 紅葉 | KUREHA
    bio: '神社巡りが趣味の一般人'
    about: 
  params:
    dateFormat: '2006-01-02'

en:
  languageName: English
  title: Shinto Database
  hasCJKLanguage: true
  weight: 2
  author:
    name: KUREHA | 紅葉
    bio: 'Hobbies: visiting shinto shrines and traveling'
  params:
    dateFormat: '2006-01-02'
    # brand: Shinto Database


zh-cn:
  languageName: 简体中文
  weight: 4
  params:
    dateFormat: '2006-01-02'
    description: 一个快速、响应式和功能丰富的 Hugo 博客主题
    keywords: 'Hugo, Bootstrap, 博客主题'
    archive:
      dateFormat: 01-02
