markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false

  defaultMarkdownHandler: goldmark

  goldmark:

    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true

    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github

    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: false
    noHl: false
    # style: monokai
    tabWidth: 2

  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
