main:
  - name: 巡礼記
    identifier: blog
    pre: '<i class="fas fa-fw fa-blog me-1"></i>'


footer:
  - name: ""
    identifier: "info"
    weight: 1
#  - name: プライバシーポリシー
#    identifier: "privacy-policy"
#    weight: 2
#    parent: "support"
#    url: /privacy-policy/index.md
